# Generated by Django 4.1.4 on 2022-12-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_answer_question_remove_question_test_and_more'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, to='questions.question'),
        ),
    ]
